# Generated by Django 5.2.14 on 2026-06-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('cat', models.CharField(max_length=100)),
                ('span', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
