# Generated by Django 5.2.14 on 2026-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('val_1_2', models.CharField(max_length=100)),
                ('val_3_4', models.CharField(max_length=100)),
                ('val_5_6', models.CharField(max_length=100)),
                ('val_7_8', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StandardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age_group', models.CharField(max_length=100)),
                ('objectives', models.TextField()),
                ('weekly_plan', models.TextField()),
                ('assessment', models.TextField()),
            ],
        ),
    ]
