# Generated by Django 5.2.14 on 2026-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_featureitem_programitem_whyarcheryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='google_maps_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
