# Generated by Django 5.2.14 on 2026-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_center_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
