# Generated by Django 5.2.14 on 2026-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_enrollment_aadhar_no_enrollment_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
